name: yudhisav
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: 
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  video_player: ^2.7.0

  google_sign_in: ^6.1.5
  flutter_signin_button: ^2.0.0
  image_picker: ^1.0.4
  firebase_storage: ^12.4.7
  intl: ^0.19.0 
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/images/loginimage.png
    - assets/images/google_icon.png
    - assets/images/house.png
    - assets/images/book-open-text.png
    - assets/images/user.png
    - assets/images/circle-help.png
    - assets/images/history.png
    - assets/images/job.png


  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
